#! /bin/sh

case "$1" in
  start)
     echo -n "Loading Scull"
     chmod 775 /etc/scull_load
     chmod 775 /etc/module_load
     chmod 775 /etc/scull_unload
     chmod 775 /etc/module_unload
     chmod 775 /etc/aesdchar_load

     /etc/scull_load
     echo "."

     echo "Loading Faulty"
     /etc/module_load
     echo "."

     echo "Loading Aesd char driver"
     /etc/aesdchar_load
     echo "."

     echo "Loading Hello"
     modprobe hello
     echo "."

     ;;
  stop)
     echo "Unloading Scull"
     /etc/scull/scull_unload
     echo "."

     echo "Unloading Faulty"
     /etc/misc-modules/module_unload
     echo "."

     echo "Unloading Hello"
     rmmod hello
     echo "."

     echo "Unloading Aesd char driver"
     /etc/aesdchar_unload
     echo "."

     ;;
  *)
     echo "Usage: $0 {start|stop|restart|force-reload}"
     exit 1
esac

exit 0